name: Cucumber

on:
  pull_request:
    branches:
      - main
      - develop

  push:
    branches:
      - main
      - develop
      - 'feature/**'
    tags:
      - '**'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Configurando Repositorio
        uses: actions/checkout@v3

      - name: Configurando Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Configure WebDriver for Chrome
        uses: nanasess/setup-chromedriver@v1
        with:
          chromedriver-version: '102.0.5005.61'

      - name: Executando Test
        run: mvn test

      - name: Gerando Relatorio
        run: mvn verify -DskipTests

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'target/cucumber-reports/cucumber-html-reports'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

      - name: Link Relatorio
        run: echo 'https://netosiqueira.github.io/Desafio-GroceryCrud/feature-overview.html'
